/** Код жанра -> название на русском. Подключается при сборке, без потери скорости. */
export const GENRES_MAP = {
  "about_musicians": "О музыкантах",
  "adv_animal": "Приключения с животными",
  "adv_geo": "Географические приключения",
  "adv_history": "Исторические приключения",
  "adv_indian": "Приключения об индейцах",
  "adv_maritime": "Морские приключения",
  "adv_modern": "Современные приключения",
  "adv_story": "Приключенческая проза",
  "adventure": "Приключения",
  "adventure_fantasy": "Приключенческое фэнтези",
  "antique": "Античная литература",
  "antique_ant": "Античная литература",
  "antique_east": "Восточная античная литература",
  "antique_eastern": "Восточная античная литература",
  "antique_european": "Европейская античная литература",
  "antique_myths": "Мифы и легенды",
  "antique_russian": "Древнерусская литература",
  "aphorisms": "Афоризмы",
  "architecture": "Литература об архитектуре",
  "architecture_book": "Литература об архитектуре",
  "art_criticism": "Искусствоведение",
  "art_and_culture": "Искусство и культура",
  "art_world_culture": "Искусство и культура",
  "asian_fantasy": "Азиатское фэнтези",
  "astrology": "Астрология",
  "auto_business": "Автомобильный бизнес",
  "automotive_business": "Автомобильный бизнес",
  "auto_regulations": "Автомобильные правила",
  "automotive_regulations": "Автомобильные правила",
  "banking": "Банковское дело",
  "boyar_anime": "Бояр-аниме",
  "child_adv": "Детские приключения",
  "children_adventure": "Детские приключения",
  "child_adv_animal": "Детские приключения с животными",
  "children_animal_adventure": "Детские приключения с животными",
  "child_classical": "Детская классика",
  "children_classics": "Детская классика",
  "child_det": "Детский детектив",
  "children_detective": "Детский детектив",
  "child_det_animal_detectives": "Детский детектив о животных",
  "children_animal_detective": "Детский детектив о животных",
  "child_det_children_detectives": "Детский детектив о юных сыщиках",
  "children_young_detective": "Детский детектив о юных сыщиках",
  "child_det_other": "Другой детский детектив",
  "child_dramaturgy": "Детская драматургия",
  "children_dramaturgy": "Детская драматургия",
  "child_education": "Детская образовательная литература",
  "children_education": "Детская образовательная литература",
  "child_folklore": "Детский фольклор",
  "children_folklore": "Детский фольклор",
  "child_prose": "Детская проза",
  "children_prose": "Детская проза",
  "child_prose_history": "Детская историческая проза",
  "children_historical_prose": "Детская историческая проза",
  "child_prose_humor": "Детская юмористическая проза",
  "children_humorous_prose": "Детская юмористическая проза",
  "child_prose_romantic": "Детская романтическая проза",
  "children_romantic_prose": "Детская романтическая проза",
  "child_sf": "Детская научная фантастика",
  "children_science_fiction": "Детская научная фантастика",
  "child_sf_fantasy": "Детское фэнтези",
  "children_fantasy": "Детское фэнтези",
  "child_sf_horror": "Детские ужасы",
  "children_horror": "Детские ужасы",
  "child_sf_hronoopera": "Детская хроноопера",
  "children_time_travel": "Детское. Путешествие во времени",
  "hronoopera": "Хроноопера",
  "time_travel": "Путешествие во времени",
  "child_sf_space": "Детская космическая фантастика",
  "children_space_opera": "Детская космическая фантастика",
  "child_tale": "Детская сказка",
  "children_fairy_tale": "Детская сказка",
  "child_tale_foreign_writers": "Детская сказка иностранных авторов",
  "children_foreign_fairy_tale": "Детская сказка иностранных авторов",
  "child_tale_rus": "Русская детская сказка",
  "children_russian_fairy_tale": "Русская детская сказка",
  "child_tale_russian_writers": "Детская сказка русских авторов",
  "child_verse": "Детская поэзия",
  "children_poetry": "Детская поэзия",
  "children": "Детская литература",
  "children_literature": "Детская литература",
  "cine": "Литература о кинематографе",
  "cinema": "Литература о кинематографе",
  "comedy": "Комедия",
  "comics": "Комиксы",
  "comp_db": "Компьютерные базы данных",
  "computer_databases": "Компьютерные базы данных",
  "comp_hard": "Компьютерное оборудование",
  "computer_hardware": "Компьютерное оборудование",
  "comp_www": "Литература об интернете",
  "computer_internet": "Литература об интернете",
  "computer_translation": "Компьютерный перевод",
  "computers": "Литература о компьютерах",
  "dark_fantasy": "Тёмное фэнтези",
  "design": "Литература о дизайне",
  "det_action": "Боевик-детектив",
  "action_detective": "Боевик-детектив",
  "det_artifact": "Детектив об артефактах",
  "artifact_detective": "Детектив об артефактах",
  "det_classic": "Классический детектив",
  "classic_detective": "Классический детектив",
  "det_crime": "Криминальный детектив",
  "crime_detective": "Криминальный детектив",
  "det_espionage": "Шпионский детектив",
  "espionage_detective": "Шпионский детектив",
  "det_hard": "Жёсткий детектив",
  "hardboiled_detective": "Жёсткий детектив",
  "det_history": "Исторический детектив",
  "historical_detective": "Исторический детектив",
  "det_irony": "Иронический детектив",
  "ironic_detective": "Иронический детектив",
  "det_lady": "Дамский детектив",
  "cozy_detective": "Уютный детектив",
  "det_maniac": "Детектив о маньяках",
  "det_police": "Полицейский детектив",
  "police_detective": "Полицейский детектив",
  "det_political": "Политический детектив",
  "political_detective": "Политический детектив",
  "det_su": "Советский детектив",
  "soviet_detective": "Советский детектив",
  "detective": "Детектив",
  "dorama": "Дорама",
  "drama": "Драма",
  "drama_antique": "Античная драма",
  "antique_drama": "Античная драма",
  "dramaturgy": "Драматургия",
  "dystopian": "Антиутопия",
  "dystopia": "Антиутопия",
  "economics": "Экономика",
  "economics_ref": "Экономические справочники",
  "economics_reference": "Экономические справочники",
  "epic": "Эпическая литература",
  "epic_literature": "Эпическая литература",
  "epistolary_fiction": "Эпистолярная литература",
  "equ_history": "История Эквестрии",
  "equestrian_history": "История Эквестрии",
  "everyday_fantasy": "Бытовое фэнтези",
  "fairy_fantasy": "Сказочное фэнтези",
  "fairy_tale_fantasy": "Сказочное фэнтези",
  "family": "Литература о доме и семье",
  "home_and_family": "Литература о доме и семье",
  "home": "Литература о доме и семье",
  "home_collecting": "Литература о коллекционировании",
  "collecting": "Литература о коллекционировании",
  "home_cooking": "Кулинария",
  "cooking": "Кулинария",
  "home_crafts": "Ремёсла",
  "crafts": "Ремёсла",
  "home_diy": "Сделай сам",
  "diy": "Сделай сам",
  "home_entertain": "Развлечения",
  "entertainment": "Развлечения",
  "home_garden": "Садоводство",
  "gardening": "Садоводство",
  "home_health": "Здоровье",
  "health": "Здоровье",
  "home_pets": "Домашние животные",
  "pets": "Домашние животные",
  "home_sex": "Секс и отношения",
  "sex_and_relationships": "Секс и отношения",
  "home_sport": "Спорт",
  "sports": "Спорт",
  "humor": "Юмор",
  "humor_anecdote": "Анекдоты",
  "humorous_anecdotes": "Анекдоты",
  "humor_prose": "Юмористическая проза",
  "humorous_prose": "Юмористическая проза",
  "humor_satire": "Сатира",
  "satire": "Сатира",
  "humor_verse": "Юмористическая поэзия",
  "humorous_poetry": "Юмористическая поэзия",
  "limerick": "Лимерик",
  "literature_18": "Литература XVIII века",
  "eighteenth_century_literature": "Литература XVIII века",
  "literature_19": "Литература XIX века",
  "nineteenth_century_literature": "Литература XIX века",
  "literature_20": "Литература XX века",
  "twentieth_century_literature": "Литература XX века",
  "love": "Любовный роман",
  "romance": "Любовный роман",
  "love_contemporary": "Современный любовный роман",
  "contemporary_romance": "Современный любовный роман",
  "love_detective": "Любовный детектив",
  "romance_detective": "Любовный детектив",
  "love_erotica": "Эротический роман",
  "erotic_romance": "Эротический роман",
  "love_hard": "Тёмный любовный роман",
  "dark_romance": "Тёмный любовный роман",
  "love_history": "Исторический любовный роман",
  "historical_romance": "Исторический любовный роман",
  "love_sf": "Фантастический любовный роман",
  "science_fiction_romance": "Фантастический любовный роман",
  "love_short": "Короткий любовный роман",
  "short_romance": "Короткий любовный роман",
  "lyrics": "Лирическая поэзия",
  "lyrical_poetry": "Лирическая поэзия",
  "magic_school": "Фэнтези о школе магии",
  "magic_school_fantasy": "Фэнтези о школе магии",
  "military_history": "Военная история",
  "military_special": "Специальная военная литература",
  "military_weapon": "Литература об оружии",
  "military_weapons": "Литература об оружии",
  "modern_tale": "Современная сказка",
  "modern_fairy_tale": "Современная сказка",
  "music": "Литература о музыке",
  "network_literature": "Сетевая литература",
  "online_literature": "Сетевая литература",
  "nonf_biography": "Биография",
  "biography": "Биография",
  "nonf_biography_celebrities": "Биография знаменитостей",
  "celebrity_biography": "Биография знаменитостей",
  "nonf_biography_historical": "Биография исторических личностей",
  "historical_biography": "Биография исторических личностей",
  "nonf_biography_military_figures": "Биография военных деятелей",
  "military_biography": "Биография военных деятелей",
  "nonf_biography_writers": "Биография писателей",
  "writer_biography": "Биография писателей",
  "nonf_criticism": "Литературная критика",
  "literary_criticism": "Литературная критика",
  "nonf_military": "Военная нехудожественная литература",
  "military_nonfiction": "Военная нехудожественная литература",
  "nonf_publicism": "Публицистика",
  "publicism": "Публицистика",
  "nonfiction": "Нехудожественная литература",
  "notes": "Заметки",
  "nsf": "Ненаучная фантастика",
  "new_age_fiction": "Ненаучная фантастика",
  "org_behavior": "Организационное поведение",
  "organizational_behavior": "Организационное поведение",
  "other": "Другое",
  "overdrive[p]": "Overdrive",
  "painting": "Литература о живописи",
  "palindromes": "Палиндромы",
  "periodic": "Периодическая литература",
  "periodicals": "Периодическая литература",
  "poem": "Поэзия",
  "poetry": "Поэзия",
  "poetry_classical": "Классическая поэзия",
  "classical_poetry": "Классическая поэзия",
  "poetry_east": "Восточная поэзия",
  "eastern_poetry": "Восточная поэзия",
  "poetry_for_classical": "Классическая поэзия",
  "poetry_for_modern": "Современная поэзия",
  "poetry_modern": "Современная поэзия",
  "modern_poetry": "Современная поэзия",
  "poetry_rus_classical": "Русская классическая поэзия",
  "russian_classical_poetry": "Русская классическая поэзия",
  "poetry_rus_modern": "Русская современная поэзия",
  "russian_mod_poetry": "Русская современная поэзия",
  "popadancy": "Попаданцы",
  "isekai": "Попаданцы",
  "popular_business": "Деловая литература",
  "business_literature": "Деловая литература",
  "prose": "Проза",
  "prose_abs": "Абсурдистская проза",
  "absurdist_prose": "Абсурдистская проза",
  "prose_classic": "Классическая проза",
  "classical_prose": "Классическая проза",
  "prose_contemporary": "Современная проза",
  "contemporary_prose": "Современная проза",
  "prose_counter": "Контркультурная проза",
  "counterculture_prose": "Контркультурная проза",
  "prose_game": "Игровая проза",
  "game_fiction": "Игровая проза",
  "prose_history": "Историческая проза",
  "historical_prose": "Историческая проза",
  "prose_magic": "Магическая проза",
  "magical_prose": "Магическая проза",
  "prose_military": "Военная проза",
  "military_prose": "Военная проза",
  "prose_neformatny": "Неформатная проза",
  "experimental_prose": "Экспериментальная проза",
  "prose_rus_classic": "Русская классическая проза",
  "russian_classical_prose": "Русская классическая проза",
  "prose_su_classics": "Советская классическая проза",
  "soviet_classical_prose": "Советская классическая проза",
  "proverbs": "Пословицы",
  "ref_dict": "Словари",
  "dictionary": "Словари",
  "ref_encyc": "Энциклопедии",
  "encyclopedia": "Энциклопедии",
  "ref_guide": "Руководства",
  "guide": "Руководства",
  "ref_ref": "Справочная литература",
  "reference": "Справочная литература",
  "religion": "Религия",
  "religion_budda": "Буддизм",
  "buddhism": "Буддизм",
  "religion_catholicism": "Католицизм",
  "catholicism": "Католицизм",
  "religion_christianity": "Христианство",
  "christianity": "Христианство",
  "religion_esoterics": "Эзотерика",
  "esotericism": "Эзотерика",
  "religion_hinduism": "Индуизм",
  "hinduism": "Индуизм",
  "religion_islam": "Ислам",
  "islam": "Ислам",
  "religion_judaism": "Иудаизм",
  "judaism": "Иудаизм",
  "religion_orthodoxy": "Православие",
  "orthodoxy": "Православие",
  "religion_paganism": "Язычество",
  "paganism": "Язычество",
  "religion_protestantism": "Протестантизм",
  "protestantism": "Протестантизм",
  "religion_self": "Духовное саморазвитие",
  "spiritual_self_help": "Духовное саморазвитие",
  "russian_fantasy": "Русское фэнтези",
  "sci_biology": "Биология",
  "biology": "Биология",
  "sci_botany": "Ботаника",
  "botany": "Ботаника",
  "sci_build": "Строительство",
  "construction": "Строительство",
  "sci_chem": "Химия",
  "chemistry": "Химия",
  "sci_cosmos": "Астрономия",
  "astronomy": "Астрономия",
  "sci_culture": "Культурология",
  "cultural_studies": "Культурология",
  "sci_ecology": "Экология",
  "ecology": "Экология",
  "sci_economy": "Экономика (научная)",
  "economics_science": "Экономика (научная)",
  "sci_geo": "География",
  "geography": "География",
  "sci_history": "История",
  "history": "История",
  "sci_juris": "Юриспруденция",
  "law": "Юриспруденция",
  "sci_linguistic": "Лингвистика",
  "linguistics": "Лингвистика",
  "sci_math": "Математика",
  "mathematics": "Математика",
  "sci_medicine": "Медицина",
  "medicine": "Медицина",
  "sci_medicine_alternative": "Альтернативная медицина",
  "alternative_medicine": "Альтернативная медицина",
  "sci_metal": "Металлургия",
  "metallurgy": "Металлургия",
  "sci_oriental": "Востоковедение",
  "oriental_studies": "Востоковедение",
  "sci_pedagogy": "Педагогика",
  "pedagogy": "Педагогика",
  "sci_philology": "Филология",
  "philology": "Филология",
  "sci_philosophy": "Философия",
  "philosophy": "Философия",
  "sci_phys": "Физика",
  "physics": "Физика",
  "sci_politics": "Политология",
  "political_science": "Политология",
  "sci_popular": "Популярная наука",
  "popular_science": "Популярная наука",
  "sci_psychology": "Психология",
  "psychology": "Психология",
  "sci_psychology_popular": "Популярная психология",
  "popular_psychology": "Популярная психология",
  "sci_radio": "Радиоэлектроника",
  "radio_electronics": "Радиоэлектроника",
  "sci_religion": "Религиоведение",
  "religious_studies": "Религиоведение",
  "sci_social_studies": "Социология",
  "sociology": "Социология",
  "sci_state": "Государственное управление",
  "political_studies": "Государственное управление",
  "sci_tech": "Техника",
  "technology": "Техника",
  "sci_textbook": "Учебники",
  "textbook": "Учебники",
  "sci_theories": "Научные теории",
  "scientific_theories": "Научные теории",
  "sci_transport": "Транспорт",
  "transportation": "Транспорт",
  "sci_veterinary": "Ветеринария",
  "veterinary_science": "Ветеринария",
  "sci_zoo": "Зоология",
  "zoology": "Зоология",
  "science": "Наука",
  "screenplays": "Сценарии",
  "sf": "Научная фантастика",
  "science_fiction": "Научная фантастика",
  "sf_action": "Боевая научная фантастика",
  "science_fiction_action": "Боевая научная фантастика",
  "sf_cyberpunk": "Киберпанк",
  "cyberpunk": "Киберпанк",
  "sf_detective": "Фантастический детектив",
  "science_fiction_detective": "Фантастический детектив",
  "sf_epic": "Эпическая научная фантастика",
  "science_fiction_epic": "Эпическая научная фантастика",
  "sf_etc": "Прочая научная фантастика",
  "sf_fantasy": "Научное фэнтези",
  "science_fiction_fantasy": "Научное фэнтези",
  "sf_fantasy_city": "Городское фэнтези",
  "urban_fantasy": "Городское фэнтези",
  "sf_heroic": "Героическое фэнтези",
  "heroic_fantasy": "Героическое фэнтези",
  "sf_history": "Историческая научная фантастика",
  "science_fiction_history": "Историческая научная фантастика",
  "sf_horror": "Научная фантастика, ужасы",
  "science_fiction_horror": "Научная фантастика, ужасы",
  "sf_humor": "Юмористическая научная фантастика",
  "science_fiction_humor": "Юмористическая научная фантастика",
  "sf_litrpg": "ЛитРПГ",
  "litrpg": "ЛитРПГ",
  "sf_mystic": "Мистическая научная фантастика",
  "science_fiction_mystic": "Мистическая научная фантастика",
  "sf_postapocalyptic": "Постапокалиптика",
  "postapocalyptic": "Постапокалиптика",
  "sf_realrpg": "РеалРПГ",
  "realrpg": "РеалРПГ",
  "sf_social": "Социальная научная фантастика",
  "social_science_fiction": "Социальная научная фантастика",
  "sf_space": "Космическая опера",
  "space_opera": "Космическая опера",
  "sf_stimpank": "Стимпанк",
  "steampunk": "Стимпанк",
  "sf_su": "Советская научная фантастика",
  "soviet_science_fiction": "Советская научная фантастика",
  "sf_technofantasy": "Технофэнтези",
  "techno_fantasy": "Технофэнтези",
  "slavic_fantasy": "Славянское фэнтези",
  "song_poetry": "Песенная поэзия",
  "story": "Рассказ",
  "short_story": "Рассказ",
  "tale_chivalry": "Рыцарская сказка",
  "chivalric_tale": "Рыцарская сказка",
  "tbg_computers": "Учебники по компьютерам",
  "computer_textbooks": "Учебники по компьютерам",
  "tbg_higher": "Учебники для высшего образования",
  "higher_education": "Учебники для высшего образования",
  "tbg_school": "Школьные учебники",
  "school_textbooks": "Школьные учебники",
  "tbg_secondary": "Учебники для среднего образования",
  "secondary_education": "Учебники для среднего образования",
  "theatre": "Театральная литература",
  "theater": "Театральная литература",
  "thriller": "Триллер",
  "tragedy": "Трагедия",
  "travel_notes": "Путевые заметки",
  "ty studené hračky[a]": "Ty studené hračky",
  "unfinished": "Незавершённые произведения",
  "utopia": "Утопия",
  "vaudeville": "Водевиль"
};
